//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by O_Pivot.rc
//
#define IDC_HELP_LIST                   1000
#define IDC_STRUCTURE                   1000
#define IDC_WRIST                       1000
#define IDC_NAME                        1001
#define IDC_JOINT1                      1001
#define IDC_ARM                         1001
#define IDC_JOINT2                      1002
#define IDC_MODEL                       1002
#define IDC_JOINT3                      1003
#define IDC_LIBRARY_PATH                1003
#define IDC_JOINT4                      1004
#define IDC_LIBRARY_BROWSE              1004
#define IDC_CREATE                      1005
#define IDC_JOINT5                      1005
#define IDC_JOINT6                      1006
#define IDC_PAR_NAME_1                  1006
#define IDC_JOINT7                      1007
#define IDC_PAR_NAME_2                  1007
#define IDC_JOINT8                      1008
#define IDC_PAR_NAME_3                  1008
#define IDC_LINK1                       1009
#define IDC_PAR_NAME_4                  1009
#define IDC_LINK2                       1010
#define IDC_PAR_NAME_5                  1010
#define IDC_LINK3                       1011
#define IDC_PAR_VALUE_1                 1011
#define IDC_LINK4                       1012
#define IDC_PAR_VALUE_2                 1012
#define IDC_LINK5                       1013
#define IDC_PAR_VALUE_3                 1013
#define IDC_LINK6                       1014
#define IDC_PAR_VALUE_4                 1014
#define IDC_LINK7                       1015
#define IDC_PAR_VALUE_5                 1015
#define IDC_LINK8                       1016
#define IDC_PICTURE                     1016
#define IDC_JOINT_BASE                  1017
#define IDC_BASE_JOINT                  1017
#define IDC_X_BASE                      1017
#define IDC_LEG_HEIGHT                  1018
#define IDC_Y_BASE                      1018
#define IDC_WRIST_SWIVEL                1019
#define IDC_Z_BASE                      1019
#define IDC_WRIST_LENGTH                1020
#define IDC_AZIM                        1020
#define IDC_GRIPPER_ROLL                1021
#define IDC_ELEV                        1021
#define IDC_GRIPPER_BASE                1022
#define IDC_ROLL                        1022
#define IDC_BABY_LEN                    1023
#define IDC_J_X                         1024
#define IDC_J_Y                         1025
#define IDC_J_Z                         1026
#define IDC_MASS                        1027
#define IDC_DEFAULT                     1028
#define IDC_BASE_PARS                   1030
#define IDC_LEG_PARS                    1031
#define IDC_WRIST_PARS                  1032
#define IDC_GRIPPER_PARS                1033
#define IDC_LINK1_PARS                  1034
#define IDC_LINK2_PARS                  1035
#define IDC_LINK3_PARS                  1036
#define IDC_LINK4_PARS                  1037
#define IDC_LINK5_PARS                  1038
#define IDC_LINK6_PARS                  1039
#define IDC_LINK7_PARS                  1040
#define IDC_LINK8_PARS                  1041
#define IDC_BODY_LIST                   1042
#define IDC_ASSIGN_BASE                 1043
#define IDC_ASSIGN_LEG                  1044
#define IDC_ASSIGN_WRIST                1045
#define IDC_DESCRIBE                    1045
#define IDC_ASSIGN_GRIPPER              1046
#define IDC_BASE_JOINT_MIN              1046
#define IDC_ASSIGN_LINK1                1047
#define IDC_WRIST_SWIVEL_MIN            1047
#define IDC_ASSIGN_LINK2                1048
#define IDC_GRIPPER_ROLL_MIN            1048
#define IDC_ASSIGN_LINK3                1049
#define IDC_BASE_JOINT_MAX              1049
#define IDC_ASSIGN_LINK4                1050
#define IDC_WRIST_SWIVEL_MAX            1050
#define IDC_ASSIGN_LINK5                1051
#define IDC_GRIPPER_ROLL_MAX            1051
#define IDC_ASSIGN_LINK6                1052
#define IDC_ASSIGN_LINK7                1053
#define IDC_ASSIGN_LINK8                1054
#define IDC_BASE_JOINT_TEST             1076
#define IDC_WRIST_SWIVEL_TEST           1077
#define IDC_DONE                        1077
#define IDC_GRIPPER_ROLL_TEST           1078
#define IDC_MASS_LIST                   1078
#define IDC_MOVE_COEF                   1079
#define IDC_BODY_ADD                    1201
#define IDC_BODY_COPY                   1202
#define IDC_BODY_KILL                   1203
#define IDC_JOINT1_MIN                  1301
#define IDC_JOINT2_MIN                  1302
#define IDC_JOINT3_MIN                  1303
#define IDC_JOINT4_MIN                  1304
#define IDC_JOINT5_MIN                  1305
#define IDC_JOINT6_MIN                  1306
#define IDC_JOINT7_MIN                  1307
#define IDC_JOINT8_MIN                  1308
#define IDC_JOINT1_MAX                  1311
#define IDC_JOINT2_MAX                  1312
#define IDC_JOINT3_MAX                  1313
#define IDC_JOINT4_MAX                  1314
#define IDC_JOINT5_MAX                  1315
#define IDC_JOINT6_MAX                  1316
#define IDC_JOINT7_MAX                  1317
#define IDC_JOINT8_MAX                  1318
#define IDC_LINK1_MIN                   1321
#define IDC_LINK2_MIN                   1322
#define IDC_LINK3_MIN                   1323
#define IDC_LINK4_MIN                   1324
#define IDC_LINK5_MIN                   1325
#define IDC_LINK6_MIN                   1326
#define IDC_LINK7_MIN                   1327
#define IDC_LINK8_MIN                   1328
#define IDC_LINK1_MAX                   1331
#define IDC_LINK2_MAX                   1332
#define IDC_LINK3_MAX                   1333
#define IDC_LINK4_MAX                   1334
#define IDC_LINK5_MAX                   1335
#define IDC_LINK6_MAX                   1336
#define IDC_LINK7_MAX                   1337
#define IDC_LINK8_MAX                   1338
#define IDC_JOINT1_TEST                 1341
#define IDC_JOINT2_TEST                 1342
#define IDC_JOINT3_TEST                 1343
#define IDC_JOINT4_TEST                 1344
#define IDC_JOINT5_TEST                 1345
#define IDC_JOINT6_TEST                 1346
#define IDC_JOINT7_TEST                 1347
#define IDC_JOINT8_TEST                 1348
#define IDC_LINK1_TEST                  1351
#define IDC_LINK2_TEST                  1352
#define IDC_LINK3_TEST                  1353
#define IDC_LINK4_TEST                  1354
#define IDC_LINK5_TEST                  1355
#define IDC_LINK6_TEST                  1356
#define IDC_LINK7_TEST                  1357
#define IDC_LINK8_TEST                  1358

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
